[package]
name = "yz-eval"
version = "0.1.0"
edition = "2021"

[dependencies]
yz-core = { path = "../yz-core" }
yz-mcts = { path = "../yz-mcts" }
yz-infer = { path = "../yz-infer" }
thiserror = "1.0"

